// Code generated by ent, DO NOT EDIT.

package credential

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the credential type in the database.
	Label = "credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldCompsole holds the string denoting the compsole field in the database.
	FieldCompsole = "compsole"
	// FieldScorify holds the string denoting the scorify field in the database.
	FieldScorify = "scorify"
	// FieldAuthentik holds the string denoting the authentik field in the database.
	FieldAuthentik = "authentik"
	// Table holds the table name of the credential in the database.
	Table = "credentials"
)

// Columns holds all SQL columns for credential fields.
var Columns = []string{
	FieldID,
	FieldNumber,
	FieldCompsole,
	FieldScorify,
	FieldAuthentik,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "credentials"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"team_credential",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Credential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByCompsole orders the results by the compsole field.
func ByCompsole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompsole, opts...).ToFunc()
}

// ByScorify orders the results by the scorify field.
func ByScorify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScorify, opts...).ToFunc()
}

// ByAuthentik orders the results by the authentik field.
func ByAuthentik(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthentik, opts...).ToFunc()
}
