// Code generated by ent, DO NOT EDIT.

package credential

import (
	"entgo.io/ent/dialect/sql"
	"github.com/ritsec/competition-ops-bot-i/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldID, id))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v int) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldNumber, v))
}

// Compsole applies equality check predicate on the "compsole" field. It's identical to CompsoleEQ.
func Compsole(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldCompsole, v))
}

// Scorify applies equality check predicate on the "scorify" field. It's identical to ScorifyEQ.
func Scorify(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldScorify, v))
}

// Authentik applies equality check predicate on the "authentik" field. It's identical to AuthentikEQ.
func Authentik(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldAuthentik, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v int) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v int) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...int) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...int) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v int) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v int) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v int) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v int) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldNumber, v))
}

// CompsoleEQ applies the EQ predicate on the "compsole" field.
func CompsoleEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldCompsole, v))
}

// CompsoleNEQ applies the NEQ predicate on the "compsole" field.
func CompsoleNEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldCompsole, v))
}

// CompsoleIn applies the In predicate on the "compsole" field.
func CompsoleIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldCompsole, vs...))
}

// CompsoleNotIn applies the NotIn predicate on the "compsole" field.
func CompsoleNotIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldCompsole, vs...))
}

// CompsoleGT applies the GT predicate on the "compsole" field.
func CompsoleGT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldCompsole, v))
}

// CompsoleGTE applies the GTE predicate on the "compsole" field.
func CompsoleGTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldCompsole, v))
}

// CompsoleLT applies the LT predicate on the "compsole" field.
func CompsoleLT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldCompsole, v))
}

// CompsoleLTE applies the LTE predicate on the "compsole" field.
func CompsoleLTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldCompsole, v))
}

// CompsoleContains applies the Contains predicate on the "compsole" field.
func CompsoleContains(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContains(FieldCompsole, v))
}

// CompsoleHasPrefix applies the HasPrefix predicate on the "compsole" field.
func CompsoleHasPrefix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasPrefix(FieldCompsole, v))
}

// CompsoleHasSuffix applies the HasSuffix predicate on the "compsole" field.
func CompsoleHasSuffix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasSuffix(FieldCompsole, v))
}

// CompsoleEqualFold applies the EqualFold predicate on the "compsole" field.
func CompsoleEqualFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEqualFold(FieldCompsole, v))
}

// CompsoleContainsFold applies the ContainsFold predicate on the "compsole" field.
func CompsoleContainsFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContainsFold(FieldCompsole, v))
}

// ScorifyEQ applies the EQ predicate on the "scorify" field.
func ScorifyEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldScorify, v))
}

// ScorifyNEQ applies the NEQ predicate on the "scorify" field.
func ScorifyNEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldScorify, v))
}

// ScorifyIn applies the In predicate on the "scorify" field.
func ScorifyIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldScorify, vs...))
}

// ScorifyNotIn applies the NotIn predicate on the "scorify" field.
func ScorifyNotIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldScorify, vs...))
}

// ScorifyGT applies the GT predicate on the "scorify" field.
func ScorifyGT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldScorify, v))
}

// ScorifyGTE applies the GTE predicate on the "scorify" field.
func ScorifyGTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldScorify, v))
}

// ScorifyLT applies the LT predicate on the "scorify" field.
func ScorifyLT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldScorify, v))
}

// ScorifyLTE applies the LTE predicate on the "scorify" field.
func ScorifyLTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldScorify, v))
}

// ScorifyContains applies the Contains predicate on the "scorify" field.
func ScorifyContains(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContains(FieldScorify, v))
}

// ScorifyHasPrefix applies the HasPrefix predicate on the "scorify" field.
func ScorifyHasPrefix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasPrefix(FieldScorify, v))
}

// ScorifyHasSuffix applies the HasSuffix predicate on the "scorify" field.
func ScorifyHasSuffix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasSuffix(FieldScorify, v))
}

// ScorifyEqualFold applies the EqualFold predicate on the "scorify" field.
func ScorifyEqualFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEqualFold(FieldScorify, v))
}

// ScorifyContainsFold applies the ContainsFold predicate on the "scorify" field.
func ScorifyContainsFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContainsFold(FieldScorify, v))
}

// AuthentikEQ applies the EQ predicate on the "authentik" field.
func AuthentikEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEQ(FieldAuthentik, v))
}

// AuthentikNEQ applies the NEQ predicate on the "authentik" field.
func AuthentikNEQ(v string) predicate.Credential {
	return predicate.Credential(sql.FieldNEQ(FieldAuthentik, v))
}

// AuthentikIn applies the In predicate on the "authentik" field.
func AuthentikIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldIn(FieldAuthentik, vs...))
}

// AuthentikNotIn applies the NotIn predicate on the "authentik" field.
func AuthentikNotIn(vs ...string) predicate.Credential {
	return predicate.Credential(sql.FieldNotIn(FieldAuthentik, vs...))
}

// AuthentikGT applies the GT predicate on the "authentik" field.
func AuthentikGT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGT(FieldAuthentik, v))
}

// AuthentikGTE applies the GTE predicate on the "authentik" field.
func AuthentikGTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldGTE(FieldAuthentik, v))
}

// AuthentikLT applies the LT predicate on the "authentik" field.
func AuthentikLT(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLT(FieldAuthentik, v))
}

// AuthentikLTE applies the LTE predicate on the "authentik" field.
func AuthentikLTE(v string) predicate.Credential {
	return predicate.Credential(sql.FieldLTE(FieldAuthentik, v))
}

// AuthentikContains applies the Contains predicate on the "authentik" field.
func AuthentikContains(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContains(FieldAuthentik, v))
}

// AuthentikHasPrefix applies the HasPrefix predicate on the "authentik" field.
func AuthentikHasPrefix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasPrefix(FieldAuthentik, v))
}

// AuthentikHasSuffix applies the HasSuffix predicate on the "authentik" field.
func AuthentikHasSuffix(v string) predicate.Credential {
	return predicate.Credential(sql.FieldHasSuffix(FieldAuthentik, v))
}

// AuthentikEqualFold applies the EqualFold predicate on the "authentik" field.
func AuthentikEqualFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldEqualFold(FieldAuthentik, v))
}

// AuthentikContainsFold applies the ContainsFold predicate on the "authentik" field.
func AuthentikContainsFold(v string) predicate.Credential {
	return predicate.Credential(sql.FieldContainsFold(FieldAuthentik, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Credential) predicate.Credential {
	return predicate.Credential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Credential) predicate.Credential {
	return predicate.Credential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Credential) predicate.Credential {
	return predicate.Credential(sql.NotPredicates(p))
}
