// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ritsec/competition-ops-bot-i/ent/credential"
)

// Credential is the model entity for the Credential schema.
type Credential struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Team number
	Number int `json:"number,omitempty"`
	// Compsole password
	Compsole string `json:"compsole,omitempty"`
	// Scorify password
	Scorify string `json:"scorify,omitempty"`
	// Authentik password
	Authentik       string `json:"authentik,omitempty"`
	team_credential *int
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Credential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credential.FieldID, credential.FieldNumber:
			values[i] = new(sql.NullInt64)
		case credential.FieldCompsole, credential.FieldScorify, credential.FieldAuthentik:
			values[i] = new(sql.NullString)
		case credential.ForeignKeys[0]: // team_credential
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Credential fields.
func (_m *Credential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case credential.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				_m.Number = int(value.Int64)
			}
		case credential.FieldCompsole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field compsole", values[i])
			} else if value.Valid {
				_m.Compsole = value.String
			}
		case credential.FieldScorify:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scorify", values[i])
			} else if value.Valid {
				_m.Scorify = value.String
			}
		case credential.FieldAuthentik:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field authentik", values[i])
			} else if value.Valid {
				_m.Authentik = value.String
			}
		case credential.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field team_credential", value)
			} else if value.Valid {
				_m.team_credential = new(int)
				*_m.team_credential = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Credential.
// This includes values selected through modifiers, order, etc.
func (_m *Credential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Credential.
// Note that you need to call Credential.Unwrap() before calling this method if this Credential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Credential) Update() *CredentialUpdateOne {
	return NewCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Credential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Credential) Unwrap() *Credential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Credential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Credential) String() string {
	var builder strings.Builder
	builder.WriteString("Credential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", _m.Number))
	builder.WriteString(", ")
	builder.WriteString("compsole=")
	builder.WriteString(_m.Compsole)
	builder.WriteString(", ")
	builder.WriteString("scorify=")
	builder.WriteString(_m.Scorify)
	builder.WriteString(", ")
	builder.WriteString("authentik=")
	builder.WriteString(_m.Authentik)
	builder.WriteByte(')')
	return builder.String()
}

// Credentials is a parsable slice of Credential.
type Credentials []*Credential
