// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ritsec/competition-ops-bot-i/ent/credential"
	"github.com/ritsec/competition-ops-bot-i/ent/predicate"
)

// CredentialUpdate is the builder for updating Credential entities.
type CredentialUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialMutation
}

// Where appends a list predicates to the CredentialUpdate builder.
func (_u *CredentialUpdate) Where(ps ...predicate.Credential) *CredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompsole sets the "compsole" field.
func (_u *CredentialUpdate) SetCompsole(v string) *CredentialUpdate {
	_u.mutation.SetCompsole(v)
	return _u
}

// SetNillableCompsole sets the "compsole" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableCompsole(v *string) *CredentialUpdate {
	if v != nil {
		_u.SetCompsole(*v)
	}
	return _u
}

// SetScorify sets the "scorify" field.
func (_u *CredentialUpdate) SetScorify(v string) *CredentialUpdate {
	_u.mutation.SetScorify(v)
	return _u
}

// SetNillableScorify sets the "scorify" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableScorify(v *string) *CredentialUpdate {
	if v != nil {
		_u.SetScorify(*v)
	}
	return _u
}

// SetAuthentik sets the "authentik" field.
func (_u *CredentialUpdate) SetAuthentik(v string) *CredentialUpdate {
	_u.mutation.SetAuthentik(v)
	return _u
}

// SetNillableAuthentik sets the "authentik" field if the given value is not nil.
func (_u *CredentialUpdate) SetNillableAuthentik(v *string) *CredentialUpdate {
	if v != nil {
		_u.SetAuthentik(*v)
	}
	return _u
}

// Mutation returns the CredentialMutation object of the builder.
func (_u *CredentialUpdate) Mutation() *CredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(credential.Table, credential.Columns, sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Compsole(); ok {
		_spec.SetField(credential.FieldCompsole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scorify(); ok {
		_spec.SetField(credential.FieldScorify, field.TypeString, value)
	}
	if value, ok := _u.mutation.Authentik(); ok {
		_spec.SetField(credential.FieldAuthentik, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialUpdateOne is the builder for updating a single Credential entity.
type CredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialMutation
}

// SetCompsole sets the "compsole" field.
func (_u *CredentialUpdateOne) SetCompsole(v string) *CredentialUpdateOne {
	_u.mutation.SetCompsole(v)
	return _u
}

// SetNillableCompsole sets the "compsole" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableCompsole(v *string) *CredentialUpdateOne {
	if v != nil {
		_u.SetCompsole(*v)
	}
	return _u
}

// SetScorify sets the "scorify" field.
func (_u *CredentialUpdateOne) SetScorify(v string) *CredentialUpdateOne {
	_u.mutation.SetScorify(v)
	return _u
}

// SetNillableScorify sets the "scorify" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableScorify(v *string) *CredentialUpdateOne {
	if v != nil {
		_u.SetScorify(*v)
	}
	return _u
}

// SetAuthentik sets the "authentik" field.
func (_u *CredentialUpdateOne) SetAuthentik(v string) *CredentialUpdateOne {
	_u.mutation.SetAuthentik(v)
	return _u
}

// SetNillableAuthentik sets the "authentik" field if the given value is not nil.
func (_u *CredentialUpdateOne) SetNillableAuthentik(v *string) *CredentialUpdateOne {
	if v != nil {
		_u.SetAuthentik(*v)
	}
	return _u
}

// Mutation returns the CredentialMutation object of the builder.
func (_u *CredentialUpdateOne) Mutation() *CredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the CredentialUpdate builder.
func (_u *CredentialUpdateOne) Where(ps ...predicate.Credential) *CredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialUpdateOne) Select(field string, fields ...string) *CredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Credential entity.
func (_u *CredentialUpdateOne) Save(ctx context.Context) (*Credential, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialUpdateOne) SaveX(ctx context.Context) *Credential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CredentialUpdateOne) sqlSave(ctx context.Context) (_node *Credential, err error) {
	_spec := sqlgraph.NewUpdateSpec(credential.Table, credential.Columns, sqlgraph.NewFieldSpec(credential.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Credential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credential.FieldID)
		for _, f := range fields {
			if !credential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Compsole(); ok {
		_spec.SetField(credential.FieldCompsole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scorify(); ok {
		_spec.SetField(credential.FieldScorify, field.TypeString, value)
	}
	if value, ok := _u.mutation.Authentik(); ok {
		_spec.SetField(credential.FieldAuthentik, field.TypeString, value)
	}
	_node = &Credential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
