// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ritsec/competition-ops-bot-i/ent/key"
	"github.com/ritsec/competition-ops-bot-i/ent/predicate"
	"github.com/ritsec/competition-ops-bot-i/ent/user"
)

// KeyUpdate is the builder for updating Key entities.
type KeyUpdate struct {
	config
	hooks    []Hook
	mutation *KeyMutation
}

// Where appends a list predicates to the KeyUpdate builder.
func (_u *KeyUpdate) Where(ps ...predicate.Key) *KeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeys sets the "keys" field.
func (_u *KeyUpdate) SetKeys(v []string) *KeyUpdate {
	_u.mutation.SetKeys(v)
	return _u
}

// AppendKeys appends value to the "keys" field.
func (_u *KeyUpdate) AppendKeys(v []string) *KeyUpdate {
	_u.mutation.AppendKeys(v)
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *KeyUpdate) AddUserIDs(ids ...int) *KeyUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *KeyUpdate) AddUser(v ...*User) *KeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the KeyMutation object of the builder.
func (_u *KeyUpdate) Mutation() *KeyMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *KeyUpdate) ClearUser() *KeyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *KeyUpdate) RemoveUserIDs(ids ...int) *KeyUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *KeyUpdate) RemoveUser(v ...*User) *KeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *KeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(key.Table, key.Columns, sqlgraph.NewFieldSpec(key.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Keys(); ok {
		_spec.SetField(key.FieldKeys, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeys(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, key.FieldKeys, value)
		})
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   key.UserTable,
			Columns: key.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   key.UserTable,
			Columns: key.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   key.UserTable,
			Columns: key.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{key.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KeyUpdateOne is the builder for updating a single Key entity.
type KeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeyMutation
}

// SetKeys sets the "keys" field.
func (_u *KeyUpdateOne) SetKeys(v []string) *KeyUpdateOne {
	_u.mutation.SetKeys(v)
	return _u
}

// AppendKeys appends value to the "keys" field.
func (_u *KeyUpdateOne) AppendKeys(v []string) *KeyUpdateOne {
	_u.mutation.AppendKeys(v)
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *KeyUpdateOne) AddUserIDs(ids ...int) *KeyUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *KeyUpdateOne) AddUser(v ...*User) *KeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the KeyMutation object of the builder.
func (_u *KeyUpdateOne) Mutation() *KeyMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *KeyUpdateOne) ClearUser() *KeyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *KeyUpdateOne) RemoveUserIDs(ids ...int) *KeyUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *KeyUpdateOne) RemoveUser(v ...*User) *KeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the KeyUpdate builder.
func (_u *KeyUpdateOne) Where(ps ...predicate.Key) *KeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KeyUpdateOne) Select(field string, fields ...string) *KeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Key entity.
func (_u *KeyUpdateOne) Save(ctx context.Context) (*Key, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyUpdateOne) SaveX(ctx context.Context) *Key {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *KeyUpdateOne) sqlSave(ctx context.Context) (_node *Key, err error) {
	_spec := sqlgraph.NewUpdateSpec(key.Table, key.Columns, sqlgraph.NewFieldSpec(key.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Key.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, key.FieldID)
		for _, f := range fields {
			if !key.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != key.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Keys(); ok {
		_spec.SetField(key.FieldKeys, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedKeys(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, key.FieldKeys, value)
		})
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   key.UserTable,
			Columns: key.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   key.UserTable,
			Columns: key.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   key.UserTable,
			Columns: key.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Key{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{key.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
