// +build tools
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ritsec/competition-ops-bot-i/ent/schema"
	"github.com/ritsec/competition-ops-bot-i/ent/team"
	"github.com/ritsec/competition-ops-bot-i/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescLead is the schema descriptor for lead field.
	teamDescLead := teamFields[0].Descriptor()
	// team.DefaultLead holds the default value on creation for the lead field.
	team.DefaultLead = teamDescLead.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
}
