// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ritsec/competition-ops-bot-i/ent/predicate"
	"github.com/ritsec/competition-ops-bot-i/ent/team"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLead sets the "lead" field.
func (_u *TeamUpdate) SetLead(v string) *TeamUpdate {
	_u.mutation.SetLead(v)
	return _u
}

// SetNillableLead sets the "lead" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableLead(v *string) *TeamUpdate {
	if v != nil {
		_u.SetLead(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TeamUpdate) SetType(v team.Type) *TeamUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableType(v *team.Type) *TeamUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *TeamUpdate) SetNumber(v int) *TeamUpdate {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableNumber(v *int) *TeamUpdate {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *TeamUpdate) AddNumber(v int) *TeamUpdate {
	_u.mutation.AddNumber(v)
	return _u
}

// ClearNumber clears the value of the "number" field.
func (_u *TeamUpdate) ClearNumber() *TeamUpdate {
	_u.mutation.ClearNumber()
	return _u
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdate) Mutation() *TeamMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := team.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Team.type": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lead(); ok {
		_spec.SetField(team.FieldLead, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(team.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(team.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(team.FieldNumber, field.TypeInt, value)
	}
	if _u.mutation.NumberCleared() {
		_spec.ClearField(team.FieldNumber, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetLead sets the "lead" field.
func (_u *TeamUpdateOne) SetLead(v string) *TeamUpdateOne {
	_u.mutation.SetLead(v)
	return _u
}

// SetNillableLead sets the "lead" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableLead(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetLead(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TeamUpdateOne) SetType(v team.Type) *TeamUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableType(v *team.Type) *TeamUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *TeamUpdateOne) SetNumber(v int) *TeamUpdateOne {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableNumber(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *TeamUpdateOne) AddNumber(v int) *TeamUpdateOne {
	_u.mutation.AddNumber(v)
	return _u
}

// ClearNumber clears the value of the "number" field.
func (_u *TeamUpdateOne) ClearNumber() *TeamUpdateOne {
	_u.mutation.ClearNumber()
	return _u
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdateOne) Mutation() *TeamMutation {
	return _u.mutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Team entity.
func (_u *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := team.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Team.type": %w`, err)}
		}
	}
	return nil
}

func (_u *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Lead(); ok {
		_spec.SetField(team.FieldLead, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(team.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(team.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(team.FieldNumber, field.TypeInt, value)
	}
	if _u.mutation.NumberCleared() {
		_spec.ClearField(team.FieldNumber, field.TypeInt)
	}
	_node = &Team{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
