// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Key is the predicate function for key builders.
type Key func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
