// Code generated by ent, DO NOT EDIT.

package team

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLead holds the string denoting the lead field in the database.
	FieldLead = "lead"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// Table holds the table name of the team in the database.
	Table = "teams"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldLead,
	FieldType,
	FieldNumber,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "teams"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_team",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLead holds the default value on creation for the "lead" field.
	DefaultLead string
)

// Type defines the type for the "type" enum field.
type Type string

// TypeBlack is the default value of the Type enum.
const DefaultType = TypeBlack

// Type values.
const (
	TypeBlue   Type = "blue"
	TypeRed    Type = "red"
	TypeBlack  Type = "black"
	TypeWhite  Type = "white"
	TypePurple Type = "purple"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeBlue, TypeRed, TypeBlack, TypeWhite, TypePurple:
		return nil
	default:
		return fmt.Errorf("team: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Team queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLead orders the results by the lead field.
func ByLead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLead, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}
