// Code generated by ent, DO NOT EDIT.

package team

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLead holds the string denoting the lead field in the database.
	FieldLead = "lead"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldSubteam holds the string denoting the subteam field in the database.
	FieldSubteam = "subteam"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// EdgeCredential holds the string denoting the credential edge name in mutations.
	EdgeCredential = "credential"
	// Table holds the table name of the team in the database.
	Table = "teams"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "team_user"
	// RoleTable is the table that holds the role relation/edge. The primary key declared below.
	RoleTable = "team_role"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "roles"
	// CredentialTable is the table that holds the credential relation/edge.
	CredentialTable = "credentials"
	// CredentialInverseTable is the table name for the Credential entity.
	// It exists in this package in order to avoid circular dependency with the "credential" package.
	CredentialInverseTable = "credentials"
	// CredentialColumn is the table column denoting the credential relation/edge.
	CredentialColumn = "team_credential"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldLead,
	FieldType,
	FieldNumber,
	FieldSubteam,
}

var (
	// RolePrimaryKey and RoleColumn2 are the table columns denoting the
	// primary key for the role relation (M2M).
	RolePrimaryKey = []string{"team_id", "role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLead holds the default value on creation for the "lead" field.
	DefaultLead string
)

// Type defines the type for the "type" enum field.
type Type string

// TypeBlack is the default value of the Type enum.
const DefaultType = TypeBlack

// Type values.
const (
	TypeBlue   Type = "blue"
	TypeRed    Type = "red"
	TypeBlack  Type = "black"
	TypeWhite  Type = "white"
	TypePurple Type = "purple"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeBlue, TypeRed, TypeBlack, TypeWhite, TypePurple:
		return nil
	default:
		return fmt.Errorf("team: invalid enum value for type field: %q", _type)
	}
}

// Subteam defines the type for the "subteam" enum field.
type Subteam string

// Subteam values.
const (
	SubteamInfra   Subteam = "infra"
	SubteamLinux   Subteam = "linux"
	SubteamWindows Subteam = "windows"
	SubteamScoring Subteam = "scoring"
	SubteamLogging Subteam = "logging"
	SubteamStore   Subteam = "store"
	SubteamCtf     Subteam = "ctf"
	SubteamKoth    Subteam = "koth"
)

func (s Subteam) String() string {
	return string(s)
}

// SubteamValidator is a validator for the "subteam" field enum values. It is called by the builders before save.
func SubteamValidator(s Subteam) error {
	switch s {
	case SubteamInfra, SubteamLinux, SubteamWindows, SubteamScoring, SubteamLogging, SubteamStore, SubteamCtf, SubteamKoth:
		return nil
	default:
		return fmt.Errorf("team: invalid enum value for subteam field: %q", s)
	}
}

// OrderOption defines the ordering options for the Team queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLead orders the results by the lead field.
func ByLead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLead, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// BySubteam orders the results by the subteam field.
func BySubteam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubteam, opts...).ToFunc()
}

// ByUserCount orders the results by user count.
func ByUserCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserStep(), opts...)
	}
}

// ByUser orders the results by user terms.
func ByUser(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRoleCount orders the results by role count.
func ByRoleCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoleStep(), opts...)
	}
}

// ByRole orders the results by role terms.
func ByRole(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoleStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCredentialCount orders the results by credential count.
func ByCredentialCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCredentialStep(), opts...)
	}
}

// ByCredential orders the results by credential terms.
func ByCredential(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserTable, UserColumn),
	)
}
func newRoleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, RoleTable, RolePrimaryKey...),
	)
}
func newCredentialStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CredentialTable, CredentialColumn),
	)
}
