// Code generated by ent, DO NOT EDIT.

package team

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ritsec/competition-ops-bot-i/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Team {
	return predicate.Team(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Team {
	return predicate.Team(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Team {
	return predicate.Team(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Team {
	return predicate.Team(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Team {
	return predicate.Team(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Team {
	return predicate.Team(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Team {
	return predicate.Team(sql.FieldLTE(FieldID, id))
}

// Lead applies equality check predicate on the "lead" field. It's identical to LeadEQ.
func Lead(v string) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldLead, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v int) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldNumber, v))
}

// LeadEQ applies the EQ predicate on the "lead" field.
func LeadEQ(v string) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldLead, v))
}

// LeadNEQ applies the NEQ predicate on the "lead" field.
func LeadNEQ(v string) predicate.Team {
	return predicate.Team(sql.FieldNEQ(FieldLead, v))
}

// LeadIn applies the In predicate on the "lead" field.
func LeadIn(vs ...string) predicate.Team {
	return predicate.Team(sql.FieldIn(FieldLead, vs...))
}

// LeadNotIn applies the NotIn predicate on the "lead" field.
func LeadNotIn(vs ...string) predicate.Team {
	return predicate.Team(sql.FieldNotIn(FieldLead, vs...))
}

// LeadGT applies the GT predicate on the "lead" field.
func LeadGT(v string) predicate.Team {
	return predicate.Team(sql.FieldGT(FieldLead, v))
}

// LeadGTE applies the GTE predicate on the "lead" field.
func LeadGTE(v string) predicate.Team {
	return predicate.Team(sql.FieldGTE(FieldLead, v))
}

// LeadLT applies the LT predicate on the "lead" field.
func LeadLT(v string) predicate.Team {
	return predicate.Team(sql.FieldLT(FieldLead, v))
}

// LeadLTE applies the LTE predicate on the "lead" field.
func LeadLTE(v string) predicate.Team {
	return predicate.Team(sql.FieldLTE(FieldLead, v))
}

// LeadContains applies the Contains predicate on the "lead" field.
func LeadContains(v string) predicate.Team {
	return predicate.Team(sql.FieldContains(FieldLead, v))
}

// LeadHasPrefix applies the HasPrefix predicate on the "lead" field.
func LeadHasPrefix(v string) predicate.Team {
	return predicate.Team(sql.FieldHasPrefix(FieldLead, v))
}

// LeadHasSuffix applies the HasSuffix predicate on the "lead" field.
func LeadHasSuffix(v string) predicate.Team {
	return predicate.Team(sql.FieldHasSuffix(FieldLead, v))
}

// LeadEqualFold applies the EqualFold predicate on the "lead" field.
func LeadEqualFold(v string) predicate.Team {
	return predicate.Team(sql.FieldEqualFold(FieldLead, v))
}

// LeadContainsFold applies the ContainsFold predicate on the "lead" field.
func LeadContainsFold(v string) predicate.Team {
	return predicate.Team(sql.FieldContainsFold(FieldLead, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Team {
	return predicate.Team(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Team {
	return predicate.Team(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Team {
	return predicate.Team(sql.FieldNotIn(FieldType, vs...))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v int) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v int) predicate.Team {
	return predicate.Team(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...int) predicate.Team {
	return predicate.Team(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...int) predicate.Team {
	return predicate.Team(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v int) predicate.Team {
	return predicate.Team(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v int) predicate.Team {
	return predicate.Team(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v int) predicate.Team {
	return predicate.Team(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v int) predicate.Team {
	return predicate.Team(sql.FieldLTE(FieldNumber, v))
}

// NumberIsNil applies the IsNil predicate on the "number" field.
func NumberIsNil() predicate.Team {
	return predicate.Team(sql.FieldIsNull(FieldNumber))
}

// NumberNotNil applies the NotNil predicate on the "number" field.
func NumberNotNil() predicate.Team {
	return predicate.Team(sql.FieldNotNull(FieldNumber))
}

// SubteamEQ applies the EQ predicate on the "subteam" field.
func SubteamEQ(v Subteam) predicate.Team {
	return predicate.Team(sql.FieldEQ(FieldSubteam, v))
}

// SubteamNEQ applies the NEQ predicate on the "subteam" field.
func SubteamNEQ(v Subteam) predicate.Team {
	return predicate.Team(sql.FieldNEQ(FieldSubteam, v))
}

// SubteamIn applies the In predicate on the "subteam" field.
func SubteamIn(vs ...Subteam) predicate.Team {
	return predicate.Team(sql.FieldIn(FieldSubteam, vs...))
}

// SubteamNotIn applies the NotIn predicate on the "subteam" field.
func SubteamNotIn(vs ...Subteam) predicate.Team {
	return predicate.Team(sql.FieldNotIn(FieldSubteam, vs...))
}

// SubteamIsNil applies the IsNil predicate on the "subteam" field.
func SubteamIsNil() predicate.Team {
	return predicate.Team(sql.FieldIsNull(FieldSubteam))
}

// SubteamNotNil applies the NotNil predicate on the "subteam" field.
func SubteamNotNil() predicate.Team {
	return predicate.Team(sql.FieldNotNull(FieldSubteam))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Team {
	return predicate.Team(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Team {
	return predicate.Team(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.Team {
	return predicate.Team(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, RoleTable, RolePrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.Team {
	return predicate.Team(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCredential applies the HasEdge predicate on the "credential" edge.
func HasCredential() predicate.Team {
	return predicate.Team(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CredentialTable, CredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCredentialWith applies the HasEdge predicate on the "credential" edge with a given conditions (other predicates).
func HasCredentialWith(preds ...predicate.Credential) predicate.Team {
	return predicate.Team(func(s *sql.Selector) {
		step := newCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Team) predicate.Team {
	return predicate.Team(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Team) predicate.Team {
	return predicate.Team(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Team) predicate.Team {
	return predicate.Team(sql.NotPredicates(p))
}
