// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "lead", Type: field.TypeString, Default: "none"},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"blue", "red", "black", "white", "purple"}, Default: "black"},
		{Name: "number", Type: field.TypeInt, Nullable: true},
		{Name: "subteam", Type: field.TypeEnum, Nullable: true, Enums: []string{"infra", "linux", "windows", "scoring", "logging", "store", "ctf", "koth"}},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString},
		{Name: "lead", Type: field.TypeBool, Default: false},
		{Name: "team_user", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_teams_user",
				Columns:    []*schema.Column{UsersColumns[4]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TeamRoleColumns holds the columns for the "team_role" table.
	TeamRoleColumns = []*schema.Column{
		{Name: "team_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeString},
	}
	// TeamRoleTable holds the schema information for the "team_role" table.
	TeamRoleTable = &schema.Table{
		Name:       "team_role",
		Columns:    TeamRoleColumns,
		PrimaryKey: []*schema.Column{TeamRoleColumns[0], TeamRoleColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "team_role_team_id",
				Columns:    []*schema.Column{TeamRoleColumns[0]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "team_role_role_id",
				Columns:    []*schema.Column{TeamRoleColumns[1]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RolesTable,
		TeamsTable,
		UsersTable,
		TeamRoleTable,
	}
)

func init() {
	UsersTable.ForeignKeys[0].RefTable = TeamsTable
	TeamRoleTable.ForeignKeys[0].RefTable = TeamsTable
	TeamRoleTable.ForeignKeys[1].RefTable = RolesTable
}
